
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rss</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><?php
            echo "<a href='".$this->baseUrl()."/feeds/add/'> Add new RSS  </a>"; ?></li>
        <li><?php
            echo "<a class='navbar-brand' href='".$this->baseUrl()."/feeds/index/'> Home </a>"; ?></li>
 
      </ul>
      
      
    </div>
  </div>
</nav>
<div>
<?php
	
	foreach ($this->paths as $channel) {
		# code..
		echo "<pre>";
		echo $channel->title;
		// echo $path->link();
		// echo $path->pubDate();
		echo "<pre>";

	
   }



?>
</div>